#!/usr/bin/env python

import numpy as np
import matplotlib.pyplot as plt
import matplotlib

plt.rc('text', usetex=True)
font = {'family': 'serif', 'size': 15, 'serif': ['computer modern roman']}
plt.rc('font', **font)
plt.rc('legend', **{'fontsize': 16})

sizes = 2**np.arange(2, 7)
S = len(sizes)
R = 10
mode = 'MonteCarlo'

Nbetas = 101
betas = 10**np.linspace(-1, 1, Nbetas)
C = np.zeros((R, S, Nbetas))

size = 8
for s, size in enumerate(sizes):
	for bind in range(Nbetas):

		filename = 'C/C-size_' + str(size) + '-Nbetas_' + \
                    str(Nbetas) + '-bind_' + str(bind) + '.npy'
		C[:, s, bind] = np.load(filename)

dashes = [(1, 2), (2, 2), (4, 2), (4, 2, 2, 2), (None, None)]
labels = [r'N=4', r'N=8', r'N=16', r'N=32', r'N=64']
b = 0.8

fig, ax = plt.subplots(1, 1, figsize=(5, 3))
for i in range(1, 6):
	plt.plot(betas, np.mean(C[:, -i, :], axis=0),
	         color='k', dashes=dashes[-i], label=labels[-i])
	plt.fill_between(betas, np.min(
		C[:, -i, :], axis=0), np.max(C[:, -i, :], axis=0), color=[b, b, b])
ax.set_xscale("log", nonposx='clip')
plt.axis([0.5, 3.5, 0, 1.3])
plt.ylabel(r'$C/N$', fontsize=20, rotation=0, labelpad=25)
plt.xlabel(r'$\beta$', fontsize=18)
plt.legend(
	loc='upper right',
	bbox_to_anchor=(
		1.05,
		1.15),
  		fancybox=True,
 		 shadow=True)
ax.set_xticks([0.5, 1, 2, 4])
ax.get_xaxis().set_major_formatter(matplotlib.ticker.ScalarFormatter())
plt.axis([0.5, 10**0.8, 0, np.max(C[-1, :, :]) * 1.05])
plt.savefig('img/fig1b.pdf', bbox_inches='tight')
plt.show()
